# Generated by Django 5.0.7 on 2026-08-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short unique code, e.g. CALLUM-HUB, MEX-GDL-01', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('HUB', 'Callum (this hub)'), ('PARTNER', 'Partner gateway')], default='PARTNER', max_length=10)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. US, MX, DE', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('supports_air', models.BooleanField(default=True)),
                ('supports_sea', models.BooleanField(default=True)),
                ('supports_land', models.BooleanField(default=True)),
                ('inbound_webhook_url', models.URLField(blank=True, help_text='Endpoint Callum calls to push shipment updates to this gateway.')),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.OneToOneField(blank=True, help_text='Integration credential this gateway authenticates with, if external.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway', to='core.partner')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
    ]
