# Generated by Django 5.0.7 on 2026-08-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('modes', models.CharField(help_text='Comma-separated subset of AIR,SEA,LAND this transporter operates.', max_length=20)),
                ('scac_or_iata', models.CharField(blank=True, help_text='SCAC (sea/land) or IATA code (air), if applicable.', max_length=20)),
                ('coverage_countries', models.CharField(blank=True, help_text='Comma-separated ISO country codes this transporter serves.', max_length=500)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.OneToOneField(blank=True, help_text='Integration credential this transporter authenticates with, if they push data via API.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporter', to='core.partner')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
