# Generated by Django 5.0.7 on 2026-08-07 16:08

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('partner_type', models.CharField(choices=[('TRANSPORTER', 'Transporter'), ('GATEWAY', 'Partner gateway'), ('INTERNAL', 'Internal system')], max_length=20)),
                ('api_key', models.CharField(default=apps.core.models.generate_api_key, editable=False, max_length=128, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_ips', models.CharField(blank=True, help_text='Comma-separated CIDR/IP allowlist. Empty = no IP restriction.', max_length=500)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload_summary', models.CharField(blank=True, max_length=500)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
