# Generated by Django 5.0.7 on 2026-08-07 16:08

import apps.shipments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gateways', '0001_initial'),
        ('transporters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.shipments.models.new_reference, editable=False, max_length=30, unique=True)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked up'), ('IN_TRANSIT', 'In transit'), ('AT_GATEWAY', 'At gateway'), ('CUSTOMS_HOLD', 'Customs hold'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Exception'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('shipper_name', models.CharField(blank=True, max_length=150)),
                ('consignee_name', models.CharField(blank=True, max_length=150)),
                ('description_of_goods', models.CharField(blank=True, max_length=255)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pieces', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Mode-specific details (AWB/BL/waybill numbers, vessel, flight, container, etc.)')),
                ('etd', models.DateTimeField(blank=True, null=True, verbose_name='Estimated departure')),
                ('eta', models.DateTimeField(blank=True, null=True, verbose_name='Estimated arrival')),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('destination_gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_shipments', to='gateways.gateway')),
                ('origin_gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_shipments', to='gateways.gateway')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Partner (transporter or gateway) that created this shipment via the API, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_shipments', to='core.partner')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='transporters.transporter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked up'), ('IN_TRANSIT', 'In transit'), ('AT_GATEWAY', 'At gateway'), ('CUSTOMS_HOLD', 'Customs hold'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Exception'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('INTERNAL', 'Callum (internal)'), ('TRANSPORTER', 'Transporter feed'), ('GATEWAY', 'Partner gateway feed')], default='INTERNAL', max_length=15)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['mode', 'status'], name='shipments_s_mode_8911b3_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['reference'], name='shipments_s_referen_5d8526_idx'),
        ),
    ]
